name: Label size of PRs 
on: pull_request
jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@851c37f157f7d64e56f41ff5d2d80316299b2d47"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
