name: update-snyk

on:
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch: {}

jobs:
  update-snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'
      - uses: snyk/actions/setup@master
      - name: Snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor
